version: '3.3'
services:
  mysql:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
