logging:
    level:
        org:
            hibernate: ERROR
            springframework:
                web: DEBUG
server:
    port: ${PORT:8080}
    servlet:
        context-path: /api/blz-na-web
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jackson:
        mapper:
            default-view-inclusion: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
    profiles:
        active: '@spring.profiles.active@'