spring:
  h2:
    console:
      enabled:true
      path:/h2
  datasource:
    url:'jdbc:h2:file:/home/lprodrigues/testjava'
    username:testjava
    password:testjava
    driver-class-name:org.h2.Driver
  jpa:
    hibernate:
      ddl-auto:update
