spring:
    datasource:
        initialize: true
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create-drop