spring:
  data:
    mongodb:
      #authentication-database: admin
      #username: root
      #password: root
      database: teste-bw
      port: 27017
      host: localhost
  cache:
    cache-names: vaultCache
    caffeine:
      spec: expireAfterWrite=30m      