/*LOCALITY*/
INSERT INTO LOCALITY (ID, NAME) VALUES (1, 'SP');
INSERT INTO LOCALITY (ID, NAME) VALUES (2, 'MOEMA');

/*PRODUCT*/
INSERT INTO PRODUCT (ID, SKU, NAME) VALUES (1, 43264, 'L Oréal Professionnel Expert Absolut Repair Cortex Lipidium - Máscara de Reconstrução 500g');

/*WAREHOUSE*/
INSERT INTO WAREHOUSE (ID, QUANTITY, TYPE, IDLOCALITY, IDPRODUCT) VALUES (1, 12, 'ECOMMERCE', 1, 1);
INSERT INTO WAREHOUSE (ID, QUANTITY, TYPE, IDLOCALITY, IDPRODUCT) VALUES (2, 3, 'PHYSICAL_STORE', 2, 1);
