package br.com.blz.testjava.domain.entity.enums

enum class Locality(val label: String) {
    AC(label = "Acre"),
    AL(label = "Alagoas"),
    AP(label = "Amapa"),
    AM(label = "Amazonas"),
    BA(label = "Bahia"),
    CE(label = "Ceara"),
    DF(label = "Distrito Federal"),
    ES(label = "Espirito Santo"),
    GO(label = "Goias"),
    MA(label = "Maranhao"),
    MT(label = "Mato Grosso"),
    MS(label = "Mato Grosso do Sul"),
    MG(label = "Minas Gerais"),
    PA(label = "Para"),
    PB(label = "Paraiba"),
    PR(label = "Parana"),
    PE(label = "Pernambuco"),
    PI(label = "Piaui"),
    RJ(label = "Rio de Janeiro"),
    RN(label = "Rio Grande do Norte"),
    RS(label = "Rio Grande do Sul"),
    RO(label = "Rondonia"),
    RR(label = "Roraima"),
    SC(label = "Santa Catarina"),
    SP(label = "Sao Paulo"),
    SE(label = "Sergipe"),
    TO(label = "Tocantins")
}
