/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 13:53:11 GMT-03:00 2018
 */

package br.com.blz.testjava.service;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import br.com.blz.testjava.exception.BusinessException;
import br.com.blz.testjava.model.Product;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class ProductServiceImpl_ESTest extends ProductServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      Product product0 = new Product();
      product0.setSku((-1L));
      try { 
        productServiceImpl0.update(product0);
        fail("Expecting exception: BusinessException");
      
      } catch(BusinessException e) {
         verifyException("br.com.blz.testjava.service.ProductServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      // Undeclared exception!
      try { 
        productServiceImpl0.validate((Product) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         verifyException("br.com.blz.testjava.service.ProductServiceImpl", e);
      }
  }


  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      Product product0 = new Product();
      boolean boolean0 = productServiceImpl0.validateInsert(product0);
      assertFalse(boolean0);
  }


  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      Product product0 = new Product();
      product0.setSku(1L);
      boolean boolean0 = productServiceImpl0.validate(product0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      Product product0 = new Product();
      boolean boolean0 = productServiceImpl0.validate(product0);
      assertFalse(boolean0);
  }


  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProductServiceImpl productServiceImpl0 = new ProductServiceImpl();
      Product product0 = new Product();
      try { 
        productServiceImpl0.save(product0);
        fail("Expecting exception: BusinessException");
      
      } catch(BusinessException e) {
         verifyException("br.com.blz.testjava.service.ProductServiceImpl", e);
      }
  }
}
