name: Maven & Docker Deploy
on:
  release:
    types: [ created ]
jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            Dockerfile
            target/*.jar
  build-docker:
    needs: [ build-maven ]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6
      - name: Display structure of downloaded files
        run: ls -R && mv artifact/* ${{ github.workspace }}
      - name: Push to GitHub Packages Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: marcusvoltolim/test-java/test-java
          tag_with_ref: true
          push: true
